// Code generated by "stringer -type=Type"; DO NOT EDIT

package token

import "fmt"

const _Type_name = "ILLEGALEOFIDENTCONSTINTSTRINGSYMBOLASSIGNPLUSMINUSBANGASTERISKSLASHLTGTEQNOTEQNEWLINECOMMASEMICOLONDOTCOLONLPARENRPARENLBRACERBRACELBRACKETRBRACKETSCOPEDEFSELFENDIFTHENELSETRUEFALSERETURNNILMODULECLASS"

var _Type_index = [...]uint8{0, 7, 10, 15, 20, 23, 29, 35, 41, 45, 50, 54, 62, 67, 69, 71, 73, 78, 85, 90, 99, 102, 107, 113, 119, 125, 131, 139, 147, 152, 155, 159, 162, 164, 168, 172, 176, 181, 187, 190, 196, 201}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
